### ISSUE TITLE
kernel panic when recover inject

### ISSUE THREAD

**Issue by YiteGu** [chaos-mesh/chaos-driver#3]
1. source code from: wget https://github.com/chaos-mesh/chaos-driver/archive/refs/tags/v0.1.1.tar.gz
2. golang version: 1.16.15
3. Architecture: x86_64
4. OS-release: Debian 9
5. kernel version: 5.4
`Reproduction:`
1. modify scheduler: # echo ioem-mq |sudo tee /sys/block/rbd1/queue/scheduler
2. inject: # ./bin/kchaos inject ioem delay --delay 1000000000 --dev-path /dev/rbd1
Injected: 1
2. run fio to write rbd1 device
3. fio completed ok
4. recover failure: # ./bin/kchaos recover --id 1
5. kernel panic

**Comment by cwen0** [comment]
This issue has been fixed in v0.2.1
